# Generated by Django 5.0.9 on 2024-10-19 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(unique='True', verbose_name='dni')),
                ('fullname', models.CharField(max_length=50, verbose_name='fullname')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('phoneNumber', models.IntegerField(unique='True', verbose_name='phone number')),
                ('mail', models.EmailField(max_length=254, unique='True', verbose_name='mail')),
                ('customerType', models.CharField(choices=[('NORMAL', 'Normal'), ('PREMIUM', 'Premium')], help_text='Select customer type.', max_length=7)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='fullname')),
                ('position', models.CharField(choices=[('MANAGER', 'Manager'), ('ADVISOR', 'Advisor'), ('DISTRIBUTOR', 'Distributor'), ('SUPERVISOR', 'Supervisor')], help_text='Select position employee.', max_length=12)),
                ('assignedRoute', models.CharField(blank=True, max_length=100, null=True, verbose_name='Assigned Route')),
                ('branchLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='branch location')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
        ),
    ]
