# Generated by Django 5.0.9 on 2024-10-19 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='branchLocation',
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='branch'),
            preserve_default=False,
        ),
    ]
