# Generated by Django 5.0.9 on 2024-10-19 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branch_options'),
        ('persons', '0002_remove_employee_branchlocation_employee_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customerType',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('PREMIUM', 'Premium')], default=1, help_text='Select Customer Type', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='dni',
            field=models.IntegerField(unique=True, verbose_name='dni'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.IntegerField(unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('ADVISOR', 'Advisor'), ('DISTRIBUTOR', 'Distributor'), ('SUPERVISOR', 'Supervisor')], help_text='Select Position Employee', max_length=11),
        ),
    ]
