# Generated by Django 5.0.9 on 2024-10-19 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0003_alter_branch_options'),
        ('logistics', '0001_initial'),
        ('persons', '0005_alter_employee_assignedroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=6, unique=True, verbose_name='code follow')),
                ('correspondenceType', models.CharField(max_length=30, verbose_name='correspondence type')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='weight')),
                ('dimensions', models.CharField(max_length=50, verbose_name='dimensions')),
                ('shipmentDate', models.DateField(verbose_name='shipment date')),
                ('deliveryDate', models.DateField(verbose_name='delivery date')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_correspondences', to='persons.customer', verbose_name='receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_correspondences', to='persons.customer', verbose_name='sender')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'correspondence',
                'verbose_name_plural': 'correspondences',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250, verbose_name='description')),
                ('incidentDate', models.DateTimeField(verbose_name='incident date')),
                ('resolutionStatus', models.CharField(choices=[('REPORTED', 'Reported'), ('SCALED', 'Scaled'), ('IN RESOLUTION', 'In resolution'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=20)),
                ('correspondence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.correspondence', verbose_name='correspondence')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AT ORIGIN', 'At origin'), ('AT DESTINATION', 'At destination'), ('ON THE WAY', 'On the way'), ('DELIVERED', 'Delivered')], help_text='Select shipping status.', max_length=20)),
                ('dateTime', models.DateTimeField(verbose_name='date and time')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='branch')),
                ('correspondence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.correspondence', verbose_name='correspondence')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'shipping',
                'verbose_name_plural': 'shippings',
            },
        ),
    ]
