# Generated by Django 5.0.9 on 2024-10-19 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50, verbose_name='origin')),
                ('destination', models.CharField(max_length=50, verbose_name='destination')),
                ('stops', models.CharField(max_length=50, verbose_name='stops')),
            ],
            options={
                'verbose_name': 'route',
                'verbose_name_plural': 'routes',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation', models.CharField(choices=[('EXPRESS', 'Express'), ('NORMAL', 'Normal')], help_text='Select type transport', max_length=11)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='cost')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation', models.CharField(choices=[('PLANE', 'Plane'), ('TRUCK', 'Truck'), ('MOTORBIKE', 'Motorbike')], help_text='Select type transport', max_length=11)),
                ('capacity', models.IntegerField(verbose_name='capacity')),
            ],
            options={
                'verbose_name': 'transport',
                'verbose_name_plural': 'transports',
            },
        ),
        migrations.CreateModel(
            name='RouteTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50, verbose_name='origin')),
                ('destination', models.CharField(max_length=50, verbose_name='destination')),
                ('transportation', models.CharField(choices=[('PLANE', 'Plane'), ('TRUCK', 'Truck'), ('MOTORBIKE', 'Motorbike')], help_text='Select type transport', max_length=11)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.route', verbose_name='route')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.transport', verbose_name='transport')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='transport',
            field=models.ManyToManyField(through='logistics.RouteTransport', to='logistics.transport', verbose_name='RouteTransport'),
        ),
    ]
