# Generated by Django 5.0.9 on 2024-10-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_route_stops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routetransport',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='routetransport',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='routetransport',
            name='transportation',
        ),
    ]
