# Generated by Django 5.0.9 on 2024-11-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_remove_routetransport_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='transport',
        ),
        migrations.DeleteModel(
            name='RouteTransport',
        ),
        migrations.AddField(
            model_name='route',
            name='transport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logistics.transport', verbose_name='Transport'),
            preserve_default=False,
        ),
    ]
